# Generated by Django 4.1.7 on 2023-03-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
