# Generated by Django 4.1.7 on 2023-03-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
