# Generated by Django 4.1.7 on 2023-03-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_rename_department_departments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
